Lab №3 initial commit
xd6d/Node.js pull request #3
Opened 2023-05-20 23:32 UTC by xd6d

2023-05-21 15:29 UTC, nosovk commented on Lab3-Node.js-Basics/package.json
> +  "version": "1.0.0",
"type": "module" forgotten

2023-05-21 15:30 UTC, nosovk commented on Lab3-Node.js-Basics/package.json
> +    "axios": "^1.4.0",
this packet not used at backend, you can use undici (it's included in node 20) or undici.fetch if you need fetch interface

2023-05-21 15:30 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task1.ts
> +    for (let i = 0; i<array.length; i++){
for await?

2023-05-21 15:32 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task2.ts
> +    }
возможно как-то проще можно удалить элементы в массиве? Или хотя бы сократить этот код?

2023-05-21 15:33 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +const fs = require('fs')
node:fs, node:path etc...

2023-05-21 15:33 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +const input = process.argv[2]
не хватает проверок на то что этот параметр есть

2023-05-21 15:34 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +fs.mkdir(dirPath, () => {})
в целом не хватает проверки ошибок

2023-05-21 15:34 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +const fs = require('fs')
для fs кстати есть промисифицированная версия

2023-05-21 15:35 UTC, nosovk commented on Lab3-Node.js-Basics/tsconfig.json
> +    "lib": ["es6","dom"],                                /* Specify a set of bundled library declaration files that describe the target runtime environment. */
у нас же нет тут dom...

2023-05-21 15:35 UTC, nosovk commented on Lab3-Node.js-Basics/tsconfig.json
> +    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
можно что-то поближе к 2023 взять

2023-05-21 15:35 UTC, nosovk commented on Lab3-Node.js-Basics/tsconfig.json
> +    "module": "commonjs",                                /* Specify what module code is generated. */
use esm pls

2023-05-22 21:20 UTC, xd6d commented
Перепрошую за бардак. Не знав, що на один бранч лише один пул реквест і всі пуши будуть падати сюди...💀💀
4 лабораторна робота вже у іншому бранчі.

2023-05-28 14:05 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task1.ts
> +    for (let i = 0; i<array.length; i++){
for await это отдельная синтаксическая конструкция, с ней будет короче

2023-05-28 14:06 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task2.ts
> +    while (array.findIndex(toDelete) != -1)
мы тут дважды ищем одно и то же, лучше так не делать, поиск дорогая операция.

2023-05-28 14:09 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task2.ts
> +    while (array.findIndex(toDelete) != -1)
вообще кривая реализация. Можно за один проход решить судьбу каждого элемента исходного масива

2023-05-28 14:11 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +const links = JSON.parse(fs.readFileSync(input).toString())
лучше не использовать Sync метода. Есть node:fs/promise - промифицированная версия прямо стандартно есть. И ее можно через promise.all запускать в параллельно выполнение пачку операций сразу

2023-05-28 14:12 UTC, nosovk commented on Lab3-Node.js-Basics/src/Task3.ts
> +for (let i = 0; i<links.length; i++) {
вот тут лучше переписать, на map и аналоги, чтобы запускать асинхронные задачи не дожидаясь завершения предыдущих

2023-05-28 14:12 UTC, nosovk requested changes
fix comments

2024-07-02 16:16 UTC, merged